== Letsencrypt Jeedom plugin 

=== Description

Let’s Encrypt est une autorité de certification ouverte, libre et automatique.
Ce plugin Jeedom installe et configure *Let's Encrypt* afin d'instaurer un accès direct *HTTPS* à votre interface web Jeedom depuis Internet.

=== Prérequis

. Le périphérique Jeedom doit avoir accès à Internet (certbot envoie une commande à l'autorité de certification de let's Encrypt).
** Si vous avez accès au market de Jeedom depuis votre installation Jeedom, ce devrait déjà être le cas.

. Le port *443* de votre IP de connexion Internet doit être redirigée vers le port 443 de l'IP votre périphérique Jeedom.
** *Port externe(WAN)* : 443
** *IP interne de destination (LAN)* : L'adresse IP de votre Jeedom
** *Port interne* : 443
** *Protocole* : TCP
** *Service* : HTTPS
*** https://assistance.orange.fr/livebox-modem/toutes-les-livebox-et-modems/installer-et-utiliser/piloter-et-parametrer-votre-materiel/le-parametrage-avance-reseau-nat-pat-ip/configurer-des-regles-nat-pat/livebox-2-configurer-les-regles-nat-pour-l-utilisation-d-un-jeu-ou-d-une-application-serveur_18998-19118[Orange]
*** https://assistance.sfr.fr/internet-et-box/box-nb6/heberger-site-box.html[SFR]
*** https://www.astuces-pratiques.fr/informatique/ouvrir-un-port-sur-la-freebox-revolution[Free]

. Votre connexion Internet doit avoir une adresse IP *statique* ou un *DynDNS* configuré (cela doit être défini dans *Administration->Configuration->Réseaux->Accès externe* avant d'installer le plugin).

=== Installation faite par ce plugin
Ce plugin installe et configure *letsencrypt* dans la configuration par défaut de Jeedom dans *Apache* 

[IMPORTANT]
Nginx ou aucun autre serveur HTTP n'est compatible pour le moment.

* Il a été testé (jusqu'à aujourd'hui) sur une installation vierge de Jeedom 3.1.7 sur un Raspberry 3.
Cela ne devrait pas marcher si vous avez modifié manuellement votre configuration de Jeedom dans Apache ou si vous avez un proxy dans votre configuration LAN.
* Ce plugin n'est pas encore très répandu, ne l'essayez donc pas si vous ne savez pas comment configurer Apache.

=== This plugins is under AGPL 3 Licence
http://www.gnu.org/licenses/agpl-3.0.html which included following limitation of Liability:

  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.


'''
Let’s Encrypt is a free, automated, and open certificate authority brought to you by the non-profit Internet Security Research Group (ISRG).
